# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 19:30
from __future__ import unicode_literals
from datetime import datetime, timedelta

from dateutil import parser
from django.db import migrations


def import_initial_flights(apps, schema_editor):
    Manufacturer = apps.get_model('core.Manufacturer')

    boeing, _ = Manufacturer.objects.get_or_create(name='Boeing',
                                                   country='US',
                                                   city='Chicago')
    airbus, _ = Manufacturer.objects.get_or_create(name='Airbus SAS',
                                                   country='FR',
                                                   city='Tolouse')
    embarer, _ = Manufacturer.objects.get_or_create(name='Embarer',
                                                    country='BR',
                                                    city='Sao Paolo')
    tupolev, _ = Manufacturer.objects.get_or_create(name='Tupolev',
                                                 country='RU',
                                                 city='Moscow')

    AircraftMake = apps.get_model('core.AircraftMake')

    a330, _ = AircraftMake.objects.get_or_create(
        manufacturer=airbus,
        name='A330',
        capacity=254,
        length=57.5,
        speed=870
    )

    a320, _ = AircraftMake.objects.get_or_create(
        manufacturer=airbus,
        name='A320',
        capacity=174,
        length=37.5,
        speed=828
    )

    a319, _ = AircraftMake.objects.get_or_create(
        manufacturer=airbus,
        name='A319',
        capacity=144,
        length=33.8,
        speed=828
    )

    Company = apps.get_model('core.Company')
    air_serbia, _ = Company.objects.get_or_create(name="AirSerbia")

    Crew = apps.get_model('core.Crew')

    # pilots
    Crew.objects.create(username='djordjevic', sex='M')
    Crew.objects.create(username='jevdjevic', sex='M')
    Crew.objects.create(username='teodosic', sex='M')
    Crew.objects.create(username='marjanovic', sex='M')
    Crew.objects.create(username='filipovic', sex='M')
    Crew.objects.create(username='prlainovic', sex='M')

    # stewardesses
    Crew.objects.create(username='vesnavulovic', sex='F')
    Crew.objects.create(username='nadastankovic', sex='F')
    Crew.objects.create(username='dusicaspasic', sex='F')
    Crew.objects.create(username='natasamiljkovic', sex='F')
    Crew.objects.create(username='sanjapetrovic', sex='F')
    Crew.objects.create(username='majanenadic', sex='F')
    Crew.objects.create(username='katarinasreckovic', sex='F')
    Crew.objects.create(username='jovanagrbic', sex='F')
    Crew.objects.create(username='tijanadimitrijevic', sex='F')
    Crew.objects.create(username='marijapetrovic', sex='F')

    Aircraft = apps.get_model('core.Aircraft')

    Aircraft.objects.create(make=a330, company=air_serbia)
    Aircraft.objects.create(make=a320, company=air_serbia)
    Aircraft.objects.create(make=a319, company=air_serbia)
    Aircraft.objects.create(make=a319, company=air_serbia)
    Aircraft.objects.create(make=a319, company=air_serbia)

    flights = [
        {
            "FlightNo": "JU186",
            "Air": "AirSerbia",
            "DepAP": "BEG",
            "DTerm": "BEG-Terminal 2",
            "DGate": "A10",
            "ArrAP": "TIV",
            "ATerm": "TIV-Terminal 1",
            "AGate": "A1",
            "StartDate": "01/08/2017",
            "StartTime": "07:00:00 AM",
            "Duration": "00:50",
            "RouteRadar": [
                "BEG",
                "ZLA",
                "TGD",
                "TIV",
            ],
            "Charter": False,
            "IDPlane": 3,
            "Crew": [
                "jevdjevic",
                "teodosic",
                "dusicaspasic",
                "sanjapetrovic",
                "natasamiljkovic",
            ]
        },
        {
            "FlightNo": "JU187",
            "Air": "AirSerbia",
            "DepAP": "TIV",
            "DTerm": "TIV-Terminal 1",
            "DGate": "A1",
            "ArrAP": "BEG",
            "ATerm": "BEG-Terminal 2",
            "AGate": "A12",
            "StartDate": "01/08/2017",
            "StartTime": "09:00:00 AM",
            "Duration": "00:50",
            "RouteRadar": [
                "TIV",
                "TGD",
                "ZLA",
                "BEG",
            ],
            "Charter": False,
            "IDPlane": 3,
            "Crew": [
                "jevdjevic",
                "teodosic",
                "dusicaspasic",
                "sanjapetrovic",
                "natasamiljkovic",
            ]
        },
        {
            "FlightNo": "JU182",
            "Air": "AirSerbia",
            "DepAP": "BEG",
            "DTerm": "BEG-Terminal 1",
            "DGate": "A6",
            "ArrAP": "TIV",
            "ATerm": "TIV-Terminal 1",
            "AGate": "A1",
            "StartDate": "01/08/2017",
            "StartTime": "01:40:00 PM",
            "Duration": "00:45",
            "RouteRadar": [
                "BEG",
                "ZLA",
                "TGD",
                "TIV",
            ],
            "Charter": False,
            "IDPlane": 2,
            "Crew":
            [
                "filipovic",
                "prlainovic",
                "nadastankovic",
                "katarinasreckovic",
                "tijanadimitrijevic",
                "marijapetrovic",
            ]
        },
        {
            "FlightNo": "JU183",
            "Air": "AirSerbia",
            "DepAP": "TIV",
            "DTerm": "TIV-Terminal 1",
            "DGate": "A1",
            "ArrAP": "BEG",
            "ATerm": "BEG-Terminal 2",
            "AGate": "A9",
            "StartDate": "01/08/2017",
            "StartTime": "03:00:00 PM",
            "Duration": "00:45",
            "RouteRadar": [
                "TIV",
                "TGD",
                "ZLA",
                "BEG",
            ],
            "Charter": False,
            "IDPlane": 2,
            "Crew":
            [
                "prlainovic",
                "filipovic",
                "nadastankovic",
                "katarinasreckovic",
                "tijanadimitrijevic",
                "marijapetrovic",
            ]
        },
        {
            "FlightNo": "JU184",
            "Air": "AirSerbia",
            "DepAP": "BEG",
            "DTerm": "BEG-Terminal 2",
            "DGate": "A12",
            "ArrAP": "TIV",
            "ATerm": "TIV-Terminal 1",
            "AGate": "A2",
            "StartDate": "01/08/2017",
            "StartTime": "05:05:00 PM",
            "Duration": "00:50",
            "RouteRadar": [
                "BEG",
                "ZLA",
                "TGD",
                "TIV",
            ],
            "Charter": False,
            "IDPlane": 3,
            "Crew": [
                "teodosic",
                "jevdjevic",
                "dusicaspasic",
                "sanjapetrovic",
                "natasamiljkovic",
            ]
        },
        {
            "FlightNo": "JU185",
            "Air": "AirSerbia",
            "DepAP": "TIV",
            "DTerm": "TIV-Terminal 1",
            "DGate": "A2",
            "ArrAP": "BEG",
            "ATerm": "BEG-Terminal 1",
            "AGate": "A1",
            "StartDate": "01/08/2017",
            "StartTime": "06:45:00 PM",
            "Duration": "00:50",
            "RouteRadar": [
                "TIV",
                "TGD",
                "ZLA",
                "BEG",
            ],
            "Charter": False,
            "IDPlane": 3,
            "Crew": [
                "teodosic",
                "jevdjevic",
                "dusicaspasic",
                "sanjapetrovic",
                "natasamiljkovic",
            ]
        }
    ]


    Company = apps.get_model('core.Company')
    Airport = apps.get_model('core.Airport')
    Terminal = apps.get_model('core.Terminal')
    Gate = apps.get_model('core.Gate')
    Radar = apps.get_model('core.Radar')
    Aircraft = apps.get_model('core.Aircraft')

    Flight = apps.get_model('core.Flight')

    for flight_raw in flights:
        flight_no = flight_raw['FlightNo']
        company = Company.objects.get(name=flight_raw['Air'])

        departure_airport, _ = Airport.objects.get_or_create(name=flight_raw['DepAP'])
        arrival_airport, _ = Airport.objects.get_or_create(name=flight_raw['ArrAP'])
        departure_terminal, _ = Terminal.objects.get_or_create(
            name=flight_raw['DTerm'],
            airport=departure_airport
        )
        arrival_terminal, _ = Terminal.objects.get_or_create(
            name=flight_raw['ATerm'],
            airport=arrival_airport)
        departure_gate, _ = Gate.objects.get_or_create(
            name=flight_raw['DGate'],
            terminal=departure_terminal
        )
        arrival_gate, _ = Gate.objects.get_or_create(
            name=flight_raw['AGate'],
            terminal=arrival_terminal
        )
        start_time = datetime.strptime(f'{flight_raw["StartDate"]} {flight_raw["StartTime"]}',
                                        '%m/%d/%Y %I:%M:%S %p')
        d_pair = [int(t) for t in flight_raw["Duration"].split(':')]
        duration = timedelta(hours=d_pair[0], minutes=int(d_pair[1]))

        radars = []
        for radar_name in flight_raw['RouteRadar']:
            radar, _ = Radar.objects.get_or_create(name=radar_name)
            radars.append(radar)

        charter = flight_raw['Charter']
        plane = Aircraft.objects.get(id=flight_raw['IDPlane'])

        crew = []
        for crew_username in flight_raw['Crew']:
            crew.append(Crew.objects.get(username=crew_username))

        flight = Flight.objects.create(
            flight_no=flight_no,
            company=company,
            departure_airport=departure_airport,
            departure_terminal=departure_terminal,
            departure_gate=departure_gate,
            arrival_airport=arrival_airport,
            arrival_terminal=arrival_terminal,
            arrival_gate=arrival_gate,
            start_time=start_time,
            charter=charter,
            plane=plane,
            duration=duration
        )

        flight.route_radars.add(*radars)
        flight.crew.add(*crew)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_initial_flights, reverse_code=migrations.RunPython.noop)
    ]
